before_build:
  - nuget restore Monitorist\Monitorist.sln
configuration: Release
artifacts: 
  - path: appVeyorBuild.zip
    name: pump 
before_deploy:
  - beforeDeploy.cmd
deploy:
  provider: GitHub
  auth_token:
    secure: CqWatOZAITE7uTenY58ol4QEap/qkCiI6V1TiJnpW4pLPucOJrjw+QPJY5/JLUZ/ # your encrypted token from GitHub
  artifact: pump            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only  
