before_build:
  - nuget restore Monitorist\Monitorist.sln
deploy:
  provider: GitHub
  auth_token:
    secure: y7ci84jqJ9Hq611qLCNByowSPepbjoZuDJd0WAVBeltnkK1GJ7x9xrQTEmEDB1yr # your encrypted token from GitHub
  artifact: \bin\release\*.*            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only  
